version: 2

references:

  node8: &node8
    - image: circleci/node:8-browsers
  node10: &node10
    - image: circleci/node:10-browsers

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "package-lock.json" }}-{{checksum "node-version" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - v1-dependency-npm-{{ checksum "package-lock.json" }}
        - v1-dependency-npm-

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules/

  neo4j_cache_key: &neo4j_cache_key
    v1-dependency-neo4j-{{ .Environment.NEO4j_DIST }}-{{ .Environment.NEO4J_VERSION }}-{{ .Environment.APOCH_VERSION }}

  restore_neo4j: &restore_neo4j
    restore_cache:
      keys:
        - *neo4j_cache_key

  cache_neo4j: &cache_neo4j
    save_cache:
      key: *npm_cache_key
      paths:
        - ./neo4j/

  install_node_modules_steps: &install_node_modules_steps
      - checkout

      - run:
          name: Create Node/NPM cache key
          command: echo "$(node -v)\n$(npm -v)" > node-version

      - *restore_node_modules

      - run:
          name: Install dependencies
          command: npm install --no-save

      - *cache_node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .

  install_neo4j: &install_neo4j
    run:
      name: Provision neo4j
      command: |
        ./scripts/install-neo4j.sh
        ./scripts/start-neo4j.sh

  start_graphql: &start_graphql
    run:
      name: Start GraphQL Server
      command: node -r babel-register ./example/graphql-tools/movies.js
      background: true

  run_tests: &run_tests
    run:
      name: Run Tests
      command: ./node_modules/.bin/ava test/*.js

  env_neo4j33ee: &env_neo4j33ee
      NEO4j_DIST: 'enterprise'
      NEO4J_VERSION: '3.3.5'
      APOCH_VERSION: '3.3.0.2'
  env_neo4j33ce: &env_neo4j33ce
      NEO4j_DIST: 'community'
      NEO4J_VERSION: '3.3.5'
      APOCH_VERSION: '3.3.0.2'
  env_neo4j32ee: &env_neo4j32ee
      NEO4j_DIST: 'enterprise'
      NEO4J_VERSION: '3.2.10'
      APOCH_VERSION: '3.2.3.6'
  env_neo4j34ee: &env_neo4j34ee
      NEO4j_DIST: 'enterprise'
      NEO4J_VERSION: '3.4.0'
      APOCH_VERSION: '3.4.0.1'

  run_tests_steps: &run_tests_steps
    - *attach_workspace
    - *restore_neo4j
    - *install_neo4j
    - *cache_neo4j
    - *start_graphql
    - run: sleep 60
    - *run_tests

jobs:
  # Node 8
  install_for_node8:
    docker: *node8
    steps: *install_node_modules_steps

  neo4j33ee_node8:
    docker: *node8
    environment: *env_neo4j33ee
    steps: *run_tests_steps

  neo4j33ce_node8:
    docker: *node8
    environment: *env_neo4j33ce
    steps: *run_tests_steps

  neo4j32ee_node8:
    docker: *node8
    environment: *env_neo4j32ee
    steps: *run_tests_steps

  neo4j34ee_node8:
    docker: *node8
    environment: *env_neo4j34ee
    steps: *run_tests_steps

  # Node 10
  install_for_node10:
    docker: *node10
    steps: *install_node_modules_steps

  neo4j33ee_node10:
    docker: *node10
    environment: *env_neo4j33ee
    steps: *run_tests_steps

  neo4j33ce_node10:
    docker: *node10
    environment: *env_neo4j33ce
    steps: *run_tests_steps

  neo4j32ee_node10:
    docker: *node10
    environment: *env_neo4j32ee
    steps: *run_tests_steps

  neo4j34ee_node10:
    docker: *node10
    environment: *env_neo4j34ee
    steps: *run_tests_steps

workflows:
  version: 2
  integration_test:
    jobs:
      - install_for_node8
      - neo4j33ee_node8:
          requires:
            - install_for_node8
      - neo4j33ce_node8:
          requires:
            - install_for_node8
      - neo4j32ee_node8:
          requires:
            - install_for_node8
      - neo4j34ee_node8:
          requires:
            - install_for_node8

      - install_for_node10
      - neo4j33ee_node10:
          requires:
            - install_for_node10
      - neo4j33ce_node10:
          requires:
            - install_for_node10
      - neo4j32ee_node10:
          requires:
            - install_for_node10
      - neo4j34ee_node10:
          requires:
            - install_for_node10
